Work on progress

diff --git a/backpack_install b/backpack_install
--- a/backpack_install
+++ b/backpack_install
@@ -6,6 +6,7 @@
 # Backpack for Laravel installer
 ###########################
 
+# >>>>>>>> default variables >>>>>>>>>>
 # set defaults
 version="v0.3.0"
 script_name=$(basename "$0")
@@ -14,23 +15,61 @@ script_dir=$(pwd)
 laravel_dir=""
 vendor_dir="./vendor/backpack"
 illuminate_dir="./vendor/laravel/framework/src/Illuminate"
+# <<<<<<<< default variables <<<<<<<<<<
 
+# >>>>>>> event functions >>>>>>>>>>>
+# CTRL+C event handler
+on_ctrl_c() {
+    echo       # Set cursor to the next line of '^C'
+    tput cnorm # show cursor. You need this if animation is used.
+    echo "Terminated with Ctrl+C."
+    echo "Removing backpack modules ..."
+    composer remove backpack/crud
+    composer remove backpack/backupmanager
+    composer remove backpack/logmanager
+    composer remove backpack/settings
+    composer remove backpack/permissionmanager
+    composer remove backpack/pagemanager
+    composer remove backpack/menucrud
+    composer remove backpack/newscrud
+    composer remove backpack/filemanager
+    exit 1 # Don't remove. Use a number (1-255) for error code.
+}
+
+# Put this line at the beginning of your script (after functions used by event handlers).
+# Register CTRL+C event handler
+trap on_ctrl_c SIGINT ERR
+
+# <<<<<<< event functions <<<<<<<<<<<
+
+# >>>>>>>> functions >>>>>>>>>>>>>>>>>
 usage() {
     cat <<EOF
-Name: $script_name
+Name: 
+=====
+$script_name
 
-Description: This script install all Backpack for Laravel modules: 
+Description: 
+============
+This script install all Backpack for Laravel modules.
+
+Backpackforlaravel modules:
+===========================
 BackupManager, LogManager, Settings, PageManager, PermissionManager, MenuCrud, and  NewsCrud.
 
 Requirement:
+============
 You must have Laravel installed and connected to a database.
 
-Usage:  ./$script_name [ -a | -all ] [ -d path ] 
+Usage:
+======
+./$script_name [ -a | -all ] [ -d path ] 
     -a | --all      This will install all modules.
     -v | --version  Script version.
     -h | --help     Show help.
 
 Examples:
+=========
     cd to $script_name directory
     $ cd path/to/$script_name
 
@@ -44,20 +83,16 @@ Examples:
     $ ./$script_name -v
 
 Exit error status:
-    3:  Error on installing Backpack Core packages
-    4:  Error on installing BackupManager
-    5:  Error on installing LogManager
-    6:  Error on installing Settings
-    7:  Error on installing PageManager
-    8:  Error on installing PermissionManager
-    9:  Error on installing MenuCrud
-    10: Error on installing NewsCrud
-    11: Error on install FileManager
+==================
+    4:  Error
 
 EOF
     exit 2
 }
 
+# <<<<<<<< functions <<<<<<<<<<<<<<<<<
+
+# >>>>>>>> argument >>>>>>>>>>>>>>>>>>
 # -a parameter to install all
 while (($# > 0)); do
     case "$1" in
@@ -66,7 +101,7 @@ while (($# > 0)); do
         shift 2
         ;;
     -v | --version)
-        echo $version
+        echo "$version"
         exit 0
         ;;
     -a | --all)
@@ -79,6 +114,30 @@ while (($# > 0)); do
         ;;
     esac
 done
+# <<<<<<<< argument <<<<<<<<<<<<<<<<<<
+
+# >>>>>>>> main >>>>>>>>>>>>>>>>>>>>>>>>
+# Usage: import "mylib"
+function import() {
+    local file="./lib/${1}"
+    if [ -f "${file}" ]; then
+        source "${file}"
+    else
+        echo "Error: Cannot find library at: ${file}"
+        exit 1
+    fi
+}
+
+# Usage: import "filename"
+import "bp_crud"
+import "bp_backupmanager"
+import "bp_logmanager"
+import "bp_settings"
+import "bp_pagemanager"
+import "bp_permissionmanager"
+import "bp_menucrud"
+import "bp_newscrud"
+import "bp_filemanager"
 
 # if $laravel_dir is empty or doesn't exist. Exit with warning.
 if [[ -z "${laravel_dir}" || ! -d "${laravel_dir}" ]]; then
@@ -138,7 +197,7 @@ fi
 ##########################
 check_dir() {
     PACKAGE=""
-    cd "$laravel_dir" || exit
+    cd "$laravel_dir" "$script_dir" || exit
     local dir_to_check=$vendor_dir/$1
     while [[ -z "$PACKAGE" ]]; do
         if [[ "${all}" = "true" ]]; then
@@ -165,232 +224,69 @@ check_dir() {
 
 # check if .env file has DB_PASSWORD
 
+echo "$laravel_dir"
 # 1. Install Backpack Core packages
-# check if you have Backpack Core packages
+
 crud_ans=$(check_dir crud)
-echo ""
 if [[ "$crud_ans" = Y ]]; then
-    echo ""
-    echo ">>>>> Installing CRUD."
-    echo ""
-    echo '>>>>> CRUD: Running composer require backpack/crud:"4.1.*"'
-    composer require backpack/crud:"4.1.*" || exit 3
-    echo ""
-    echo '>>>>> CRUD: Running composer require backpack/generators --dev'
-    composer require backpack/generators --dev || exit 3
-    echo ""
-    echo '>>>>> CRUD: Running composer require laracasts/generators --dev'
-    composer require laracasts/generators --dev || exit 3
-    echo ""
-    echo '>>>>> CRUD: Running php artisan backpack:install'
-    php artisan backpack:install || exit 3
-    echo ""
-    echo ">>>>> CRUD installed."
-    echo ""
+    fn_crud "$laravel_dir"
 fi
 
 # 2. Install BackupManager
 backup_ans=$(check_dir backupmanager)
-echo ""
 if [[ "$backup_ans" = Y ]]; then
-    echo ""
-    echo ">>>>> Installing BackupManager."
-    echo ""
-    echo '>>>>> Running composer require backpack/backupmanager'
-    composer require backpack/backupmanager || exit 4
-    echo ""
-    echo '>>>>> Running php artisan vendor:publish'
-    php artisan vendor:publish --provider="Backpack\BackupManager\BackupManagerServiceProvider" || exit 4
-    echo ""
-    echo '>>>>> Running php artisan backpack:add-sidebar-content'
-    php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('backup') }}'><i class='nav-icon la la-hdd-o'></i> Backups</a></li>" || exit 4
-    echo ""
-    echo 'Adding backup to config/filesystems'
-    # Add a new "disk" to config/filesystems.php:
-    sed -i "/'disks'/r ${script_dir}/disk_backup.txt" ./config/filesystems.php
-    echo ""
-    echo ">>>>> BackupManager installed "
+    fn_backupmanager "$laravel_dir" "$script_dir"
 fi
 
 # 3. Install LogManager
-# If it is yes or parameter -y is given then install it else exit
 log_ans=$(check_dir logmanager)
-echo ""
 if [[ "$log_ans" = Y ]]; then
-    echo ""
-    echo ">>>>> Installing LogManager."
-    echo ""
-    echo '>>>>> Running composer require backpack/logmanager'
-    echo ""
-    composer require backpack/logmanager || exit 5
-    echo ""
-    echo 'Adding storage to config/filesystems'
-    # Add a new "disk" to config/filesystems.php:
-    sed -i "/'disks'/r ${script_dir}/disk_logmanager.txt" ./config/filesystems.php || exit 5
-    echo ""
-    # add APP_LOG=daily to .env
-    echo 'Adding APP_LOG,daily to config/app.php.'
-    sed -i "/return/r ${script_dir}/config_app_log.txt" ./config/app.php || exit 5
-    echo ""
-    echo '>>>>> Running php artisan backpack:add-sidebar-content'
-    php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('log') }}'><i class='nav-icon la la-terminal'></i> Logs</a></li>" || exit 5
-
-    # echo '>>>>> Replacing "channels" => ["single"]'
-    # ORIGINAL_STRING="channels' => ['single'],"
-    # NEW_STRING="channels' => ['daily'],"
-    # FILENAME='config/logging.php'
-    # sed -i "s/${ORIGINAL_STRING}/${NEW_STRING}/" $FILENAME || exit 5
-    echo ""
-    echo ">>>>> LogManager installed"
+    fn_logmanager "$laravel_dir" "$script_dir"
 fi
 
 # 4. Install Settings
 setting_ans=$(check_dir settings)
-echo ""
 if [[ "$setting_ans" = Y ]]; then
-    echo ""
-    echo ">>>>> Installing Settings."
-    echo ""
-    echo '>>>>> Running composer require backpack/settings'
-    composer require backpack/settings || exit 6
-    echo ""
-    echo '>>>>> Running php artisan vendor:publish --provider'
-    php artisan vendor:publish --provider="Backpack\Settings\SettingsServiceProvider" || exit 6
-    echo ""
-    echo '>>>>> Running php artisan migrate'
-    php artisan migrate || exit 6
-    echo ""
-    echo '>>>>> Running php artisan backpack:add-sidebar-content'
-    php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('setting') }}'><i class='nav-icon la la-cog'></i> <span>Settings</span></a></li>" || exit 6
-    echo ""
-    echo '>>>>> Running php artisan db:seed --class'
-    php artisan db:seed --class="Backpack\Settings\database\seeds\SettingsTableSeeder" || exit 6
-    echo ""
-    echo "Settings installed"
+    fn_settings "$laravel_dir"
 fi
 
 # 5. Install PageManager
 page_ans=$(check_dir pagemanager)
-echo ""
 if [[ "$page_ans" = Y ]]; then
-    echo ""
-    echo ">>>>> Installing PageManager."
-    echo ""
-    echo '>>>>> Adding app/PageTemplates.php'
-    pagetemp=./app/PageTemplates.php
-    if [[ ! -e $pagetemp ]]; then
-        cp "$script_dir"/PageTemplates.php "$laravel_dir"/app
-    fi
-    echo ""
-    echo '>>>>> Running composer require backpack/pagemanager'
-    composer require backpack/pagemanager || exit 7
-    echo ""
-    echo '>>>>> Running php artisan vendor:publish --provider'
-    php artisan vendor:publish --provider="Backpack\PageManager\PageManagerServiceProvider" || exit 7
-    echo ""
-    echo '>>>>> Running php artisan migrate'
-    php artisan migrate || exit 7
-    echo ""
-    echo '>>>>> Running php artisan backpack:add-sidebar-content'
-    php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('page') }}'><i class='nav-icon la la-file-o'></i> <span>Pages</span></a></li>" || exit 7
-    echo ""
-    echo '>>>>> PageManager installed'
+    fn_pagemanager "$laravel_dir" "$script_dir"
 fi
 
 # 6. Install PermissionManager
 permission_ans=$(check_dir permissionmanager)
-echo ""
 if [[ "$permission_ans" = Y ]]; then
-    echo ""
-    echo ">>>>> Installing PermissionManager."
-    echo ""
-    echo '>>>>> Running composer require backpack/permissionmanager'
-    composer require backpack/permissionmanager || exit 8
-    echo ""
-    echo '>>>>> Running php artisan vendor:publish --provider'
-    php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations" || exit 8
-    echo ""
-    echo '>>>>> Running php artisan migrate'
-    php artisan migrate || exit 8
-    echo ""
-    echo '>>>>> Running php artisan vendor:publish --provider'
-    php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config"
-    echo ""
-    echo '>>>>> Running php artisan vendor:publish --provider'
-    php artisan vendor:publish --provider="Backpack\PermissionManager\PermissionManagerServiceProvider" --tag="config" || exit 8
-    echo ""
-    echo '>>>>> Running the migraions: '
-    php artisan migrate || exit 8
-    echo ""
-    echo '>>>>> Running php artisan backpack:add-sidebar-content'
-    php artisan backpack:add-sidebar-content "<!-- Users, Roles, Permissions --><li class='nav-item nav-dropdown'><a class='nav-link nav-dropdown-toggle' href='#'><i class='nav-icon la la-users'></i> Authentication</a><ul class='nav-dropdown-items'><li class='nav-item'><a class='nav-link' href='{{ backpack_url('user') }}'><i class='nav-icon la la-user'></i> <span>Users</span></a></li><li class='nav-item'><a class='nav-link' href='{{ backpack_url('role') }}'><i class='nav-icon la la-id-badge'></i> <span>Roles</span></a></li><li class='nav-item'><a class='nav-link' href='{{ backpack_url('permission') }}'><i class='nav-icon la la-key'></i> <span>Permissions</span></a></li></ul></li>"
-    echo ""
-    echo '>>>>> PermissionManager installed.'
+    fn_permissionmanager "$laravel_dir"
 fi
+
 # 7. Install MenuCrud
 menu_ans=$(check_dir menucrud)
-echo ""
 if [[ "$menu_ans" = Y ]]; then
-    echo ">>>>> Installing MenuCRUD."
-    echo ""
-    echo '>>>>> Running composer require backpack/menucrud'
-    composer require backpack/menucrud || exit 9
-    echo ""
-    echo '>>>>> Running php artisan vendor:publish --provider'
-    php artisan vendor:publish --provider="Backpack\MenuCRUD\MenuCRUDServiceProvider" || exit 9
-    echo ""
-    echo '>>>>> Running php artisan migrate'
-    php artisan migrate || exit 9
-    echo ""
-    echo '>>>>> Running php artisan backpack:add-sidebar-content'
-    php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('menu-item') }}'><i class='nav-icon la la-list'></i> <span>Menu</span></a></li>" || exit 9
-    echo ""
-    echo '>>>>> MenuCRUD installed.'
+    fn_menucrud "$laravel_dir"
 fi
 
 # 8. Install NewsCrud
 news_ans=$(check_dir newscrud)
-echo ""
 if [[ "$news_ans" = Y ]]; then
-    echo ">>>>> Installing NewsCRUD."
-    echo ""
-    echo '>>>>> Running composer require backpack/newscrud'
-    echo ""
-    composer require backpack/newscrud || exit 10
-    echo ""
-    echo '>>>>> Running php artisan vendor:publish --provider'
-    php artisan vendor:publish --provider="Backpack\NewsCRUD\NewsCRUDServiceProvider" || exit 10
-    echo ""
-    echo '>>>>> Running php artisan migrate'
-    php artisan migrate || exit 10
-    echo ""
-    echo '>>>>> Running php artisan backpack:add-sidebar-content'
-    php artisan backpack:add-sidebar-content "<li class='nav-item nav-dropdown'><a class='nav-link nav-dropdown-toggle' href='#'><i class='nav-icon la la-newspaper-o'></i>News</a><ul class='nav-dropdown-items'><li class='nav-item'><a class='nav-link' href='{{ backpack_url('article') }}'><i class='nav-icon la la-newspaper-o'></i> Articles</a></li><li class='nav-item'><a class='nav-link' href='{{ backpack_url('category') }}'><i class='nav-icon la la-list'></i> Categories</a></li><li class='nav-item'><a class='nav-link' href='{{ backpack_url('tag') }}'><i class='nav-icon la la-tag'></i> Tags</a></li></ul></li>" || exit 10
-    echo ""
-    echo '>>>>> NewsCRUD installed.'
+    fn_newscrud "$laravel_dir"
 fi
 
 # 9. Install FileManager
 file_ans=$(check_dir filemanager)
-echo ""
 if [[ "$file_ans" = Y ]]; then
-    echo ">>>>> Installing FileManager."
-    echo '>>>>> Running composer require backpack/filemanager'
-    composer require backpack/filemanager || exit 11
-    echo ""
-    echo '>>>>> Running php artisan backpack:filemanager:install'
-    php artisan backpack:filemanager:install || exit 11
-    echo ""
-    echo '>>>>> NewsCRUD installed.'
+    fn_filemanager "$laravel_dir"
 fi
 
-echo ""
+echo
 echo "Installation completed."
-echo ""
+echo
 echo "BackupManager [optional]: You need to configure them."
-echo ""
+echo
 echo "For PermissionManager to work, add the Spatie\Permission\Traits\HasRoles trait to your User model(s)"
-echo ""
-echo ""
+echo
+echo
 echo "Happy Coding!"
 exit 0
