Moved check_dir function from lib/utils to main

diff --git a/backpack_install b/backpack_install
--- a/backpack_install
+++ b/backpack_install
@@ -124,6 +124,41 @@ import "bp_menucrud"
 import "bp_newscrud"
 import "bp_filemanager"
 
+#########################
+# Globals: $vendor_dir, $laravel_dir
+# Arguments: one of followings,
+# crud, backupmanager, filemanager, generators, logmanager,
+# menucrud, newscrud, pagemanager, permissionmanager, settings
+# Outputs: Y or N
+# Returns: 0 for success, 3 for fail
+##########################
+check_dir() {
+    PACKAGE=""
+    package_name=$1
+    laravel_dir=$2
+    script_dir=$3
+    cd "$laravel_dir" || exit
+    local dir_to_check=$laravel_dir/vendor/backpack/$package_name
+    while [[ -z "$PACKAGE" ]]; do
+        if [[ "${all}" = "true" ]]; then
+            if [[ -d "$dir_to_check" ]]; then
+                # if you have it ask if you want to overwrite
+                read -rp "It seems you already installed $1 packages. Do you want to overwrite it? yes/y or no/n.   " PACKAGE
+            else
+                PACKAGE=Y
+            fi
+        else
+            if [[ -d "$dir_to_check" ]]; then
+                # if you have it ask if you want to overwrite
+                read -rp "It seems you already installed $1 packages. Do you want to overwrite it? yes/y or no/n.   " PACKAGE
+            else
+                read -rp "Do you want to install ${1}? yes/y or no/n.   " PACKAGE
+            fi
+        fi
+    done
+
+    echo "$PACKAGE" | cut -c 1-1 | tr "[:lower:]" "[:upper:]"
+}
 # <<<<<<<< functions <<<<<<<<<<<<<<<<<
 
 # >>>>>>> event functions >>>>>>>>>>>
@@ -185,8 +220,8 @@ if [ ! "$env_ans" = Y ]; then
     exit 1
 fi
 
-# Confirm you are connected to DB and Laravel is running
-read -rp "Are you connected to DB and Laravel is running? y or n   " RUNNING
+# Confirm you are connected to DB
+read -rp "Are you connected to DB? yes/y or no/n   " RUNNING
 
 run_ans=$(echo "$RUNNING" | cut -c 1-1 | tr "[:lower:]" "[:upper:]")
 
