README Updates. Moved up usage function

diff --git a/backpack_install b/backpack_install
--- a/backpack_install
+++ b/backpack_install
@@ -16,57 +16,6 @@ laravel_dir=""
 # <<<<<<<< default variables <<<<<<<<<<
 
 # >>>>>>>> argument >>>>>>>>>>>>>>>>>>
-# -a parameter to install all
-while (($# > 0)); do
-    case "$1" in
-    -d | --dir)
-        laravel_dir=$2
-        shift 2
-        ;;
-    -v | --version)
-        echo "$version"
-        exit 0
-        ;;
-    -a | --all)
-        all=true
-        shift 1
-        ;;
-    -u | --uninstall)
-        uninstall=true
-        shift 1
-        ;;
-    -h | --help | *)
-        usage
-        exit 0
-        ;;
-    esac
-done
-# <<<<<<<< argument <<<<<<<<<<<<<<<<<<
-
-# >>>>>>>> functions >>>>>>>>>>>>>>>>>
-# Usage: import "mylib"
-function import() {
-    local file="./lib/${1}"
-    if [ -f "${file}" ]; then
-        source "${file}"
-    else
-        echo "Error: Cannot find library at: ${file}"
-        exit 1
-    fi
-}
-
-# Usage: import "filename"
-import "banners"
-import "bp_crud"
-import "bp_backupmanager"
-import "bp_logmanager"
-import "bp_settings"
-import "bp_pagemanager"
-import "bp_permissionmanager"
-import "bp_menucrud"
-import "bp_newscrud"
-import "bp_filemanager"
-
 usage() {
     cat <<EOF
 Name: 
@@ -121,6 +70,56 @@ Exit error status:
 EOF
     exit 2
 }
+
+while (($# > 0)); do
+    case "$1" in
+    -d | --dir)
+        laravel_dir=$2
+        shift 2
+        ;;
+    -v | --version)
+        echo "$version"
+        exit 0
+        ;;
+    -a | --all)
+        all=true
+        shift 1
+        ;;
+    -u | --uninstall)
+        uninstall=true
+        shift 1
+        ;;
+    -h | --help | *)
+        usage
+        exit 0
+        ;;
+    esac
+done
+# <<<<<<<< argument <<<<<<<<<<<<<<<<<<
+
+# >>>>>>>> functions >>>>>>>>>>>>>>>>>
+# Usage: import "mylib"
+function import() {
+    local file="./lib/${1}"
+    if [ -f "${file}" ]; then
+        source "${file}"
+    else
+        echo "Error: Cannot find library at: ${file}"
+        exit 1
+    fi
+}
+
+# Usage: import "filename"
+import "banners"
+import "bp_crud"
+import "bp_backupmanager"
+import "bp_logmanager"
+import "bp_settings"
+import "bp_pagemanager"
+import "bp_permissionmanager"
+import "bp_menucrud"
+import "bp_newscrud"
+import "bp_filemanager"
 
 check_cmd() {
     if [[ ! $(command -v "$1") ]]; then
