All bp files moved to bp_files. Added uninstall

diff --git a/backpack_install b/backpack_install
--- a/backpack_install
+++ b/backpack_install
@@ -13,11 +13,60 @@ script_name=$(basename "$0")
 all=""
 script_dir=$(pwd)
 laravel_dir=""
-vendor_dir="./vendor/backpack"
-illuminate_dir="./vendor/laravel/framework/src/Illuminate"
 # <<<<<<<< default variables <<<<<<<<<<
 
+# >>>>>>>> argument >>>>>>>>>>>>>>>>>>
+# -a parameter to install all
+while (($# > 0)); do
+    case "$1" in
+    -d | --dir)
+        laravel_dir=$2
+        shift 2
+        ;;
+    -v | --version)
+        echo "$version"
+        exit 0
+        ;;
+    -a | --all)
+        all=true
+        shift 1
+        ;;
+    -u | --uninstall)
+        uninstall=true
+        shift 1
+        ;;
+    -h | --help | *)
+        usage
+        exit 0
+        ;;
+    esac
+done
+# <<<<<<<< argument <<<<<<<<<<<<<<<<<<
+
 # >>>>>>>> functions >>>>>>>>>>>>>>>>>
+# Usage: import "mylib"
+function import() {
+    local file="./lib/${1}"
+    if [ -f "${file}" ]; then
+        source "${file}"
+    else
+        echo "Error: Cannot find library at: ${file}"
+        exit 1
+    fi
+}
+
+# Usage: import "filename"
+import "banners"
+import "bp_crud"
+import "bp_backupmanager"
+import "bp_logmanager"
+import "bp_settings"
+import "bp_pagemanager"
+import "bp_permissionmanager"
+import "bp_menucrud"
+import "bp_newscrud"
+import "bp_filemanager"
+
 usage() {
     cat <<EOF
 Name: 
@@ -73,39 +122,9 @@ check_cmd() {
         exit 1
     fi
 }
-# <<<<<<<< functions <<<<<<<<<<<<<<<<<
 
-# >>>>>>>> argument >>>>>>>>>>>>>>>>>>
-# -a parameter to install all
-while (($# > 0)); do
-    case "$1" in
-    -d | --dir)
-        laravel_dir=$2
-        shift 2
-        ;;
-    -v | --version)
-        echo "$version"
-        exit 0
-        ;;
-    -a | --all)
-        all=true
-        shift 1
-        ;;
-    -h | --help | *)
-        usage
-        exit 0
-        ;;
-    esac
-done
-# <<<<<<<< argument <<<<<<<<<<<<<<<<<<
-
-# >>>>>>> event functions >>>>>>>>>>>
-# CTRL+C event handler
-on_ctrl_c() {
-    echo       # Set cursor to the next line of '^C'
-    tput cnorm # show cursor. You need this if animation is used.
-    echo "Terminated with Ctrl+C."
-    echo "Removing backpack modules ..."
+uninstall_bp() {
+    laravel_dir="$1"
     cd "$laravel_dir" || exit 1
     composer remove backpack/backupmanager
     composer remove backpack/logmanager
@@ -115,90 +134,17 @@ on_ctrl_c() {
     composer remove backpack/menucrud
     composer remove backpack/newscrud
     composer remove backpack/filemanager
-    bannerColor "Please remove backpack/crud and backpack/generators manually." "yellow" "*"
-    exit 1 # Don't remove. Use a number (1-255) for error code.
+    echo "Clearing config"
+    php artisan config:clear
+    echo "Cleaning up laravel.log"
+    echo "" >"$laravel_dir"/storage/logs/laravel.log
+    bannerColor "Please run the following commands for complete uninstallation." "yellow" "*"
+    echo "$ cd $laravel_dir"
+    echo "$ git reset --"
+    echo "$ git clean -f -d"
+    echo "$ rm -rf vendor/backpack"
+    exit 0
 }
-
-# Put this line at the beginning of your script (after functions used by event handlers).
-# Register CTRL+C event handler
-trap on_ctrl_c SIGINT ERR
-
-# <<<<<<< event functions <<<<<<<<<<<
-
-# >>>>>>>> main >>>>>>>>>>>>>>>>>>>>>>>>
-# Usage: import "mylib"
-function import() {
-    local file="./lib/${1}"
-    if [ -f "${file}" ]; then
-        source "${file}"
-    else
-        echo "Error: Cannot find library at: ${file}"
-        exit 1
-    fi
-}
-
-# Usage: import "filename"
-import "bp_crud"
-import "bp_backupmanager"
-import "bp_logmanager"
-import "bp_settings"
-import "bp_pagemanager"
-import "bp_permissionmanager"
-import "bp_menucrud"
-import "bp_newscrud"
-import "bp_filemanager"
-
-# if $laravel_dir is empty or doesn't exist. Exit with warning.
-if [[ -z "${laravel_dir}" || ! -d "${laravel_dir}" ]]; then
-    bannerColor "You need to provide a correct path to your Laravel project" "red" "*"
-    exit 1
-fi
-
-# if ! type sed &>/dev/null; then
-#     bannerColor "Please install sed." "red" "*"
-#     exit 1
-# fi
-
-# cd to the project
-cd "$laravel_dir" || exit 1
-
-# check commands
-check_cmd sed
-check_cmd composer
-check_cmd laravel
-
-# check if /vendor/laravel/framework/src/Illuminate
-if [[ ! -d "$illuminate_dir" ]]; then
-    bannerColor "Please install Laravel." "red" "*"
-    exit 1
-fi
-
-# Confirm if user updated the .env file especially APP_URL
-read -rp "Have you updated .env file, like APP_URL, etc? yes/y or no/n   " ENV
-
-env_ans=$(echo "$ENV" | cut -c 1-1 | tr "[:lower:]" "[:upper:]")
-
-if [ ! "$env_ans" = Y ]; then
-    bannerColor "Update your .env file." "red" "*"
-    exit 1
-fi
-# Confirm you are connected to DB and Laravel is running
-read -rp "Are you connected to DB and Laravel is running? y or n   " RUNNING
-
-run_ans=$(echo "$RUNNING" | cut -c 1-1 | tr "[:lower:]" "[:upper:]")
-
-if [ ! "$run_ans" = Y ]; then
-    bannerColor "You need to connect to DB and run Laravel." "red" "*"
-    exit 1
-fi
-
-# if so grep const VERSION = '8.40';
-# find if it is greater than 5
-# laravelversion=$(grep VERSION ./vendor/laravel/framework/src/Illuminate/Foundation/Application.php)
-
-# echo "$laravelversion"
-
-############### functions ###########
 
 #########################
 # Globals: $vendor_dir, $laravel_dir
@@ -235,12 +181,81 @@ check_dir() {
 
     echo "$PACKAGE" | cut -c 1-1 | tr "[:lower:]" "[:upper:]"
 }
+# <<<<<<<< functions <<<<<<<<<<<<<<<<<
 
-# if laravel version is greater than 5 it's ok
+# >>>>>>> event functions >>>>>>>>>>>
+# CTRL+C event handler
+on_ctrl_c() {
+    echo       # Set cursor to the next line of '^C'
+    tput cnorm # show cursor. You need this if animation is used.
+    echo "Terminated with Ctrl+C."
+    echo "Removing backpack modules ..."
+    uninstall_bp "$laravel_dir"
+    exit 1 # Don't remove. Use a number (1-255) for error code.
+}
 
-# check if .env file has DB_PASSWORD
+# Put this line at the beginning of your script (after functions used by event handlers).
+# Register CTRL+C event handler
+trap on_ctrl_c SIGINT ERR
 
-# echo "$laravel_dir"
+# <<<<<<< event functions <<<<<<<<<<<
+
+# >>>>>>> Check >>>>>>>>>>>>>>>>>>>>>
+# cd to the project
+cd "$laravel_dir" || exit 1
+
+# if $uninstall is true run uninstall
+if [[ "$uninstall" = true ]]; then
+    # confirm if you are sure
+    read -rp "Are you sure to uninstall? yes/y or no/n   " UNINST
+
+    uninstall_ans=$(echo "$UNINST" | cut -c 1-1 | tr "[:lower:]" "[:upper:]")
+
+    if [ "$uninstall_ans" = Y ]; then
+        bannerColor "Uninstalling ..." "red" "*"
+        uninstall_bp "$laravel_dir"
+    else
+        bannerColor "Try it again." "red" "*"
+        exit 1
+    fi
+    exit 0
+fi
+
+# if $laravel_dir is empty or doesn't exist. Exit with warning.
+if [[ -z "${laravel_dir}" || ! -d "${laravel_dir}" ]]; then
+    bannerColor "You need to provide a correct path to your Laravel project" "red" "*"
+    exit 1
+fi
+
+# check commands
+check_cmd sed
+check_cmd composer
+check_cmd laravel
+
+# Confirm if user updated the .env file especially APP_URL
+read -rp "Have you updated .env file, like APP_URL, etc? yes/y or no/n   " ENV
+
+env_ans=$(echo "$ENV" | cut -c 1-1 | tr "[:lower:]" "[:upper:]")
+
+if [ ! "$env_ans" = Y ]; then
+    bannerColor "Update your .env file." "red" "*"
+    exit 1
+fi
+
+# Confirm you are connected to DB and Laravel is running
+read -rp "Are you connected to DB and Laravel is running? y or n   " RUNNING
+
+run_ans=$(echo "$RUNNING" | cut -c 1-1 | tr "[:lower:]" "[:upper:]")
+
+if [ ! "$run_ans" = Y ]; then
+    bannerColor "You need to connect to DB and run Laravel." "red" "*"
+    exit 1
+fi
+
+# <<<<<<< Check <<<<<<<<<<<<<<<<<<<<<
+
+# >>>>>>>> main >>>>>>>>>>>>>>>>>>>>>>>>
+
 # 1. Install Backpack Core packages
 
 crud_ans=$(check_dir crud)
